In [1]:
from module import *

import time


# with open('model.pkl', 'rb') as f:
#         model = pickle.load(f)

# model = load_model(checkpoint_path, MyModel, device='cuda')

In [2]:
import requests
# url = "https://apidojo-yahoo-finance-v1.p.rapidapi.com/stock/v3/get-historical-data"
# querystring = {"symbol":"BTC-USD","region":"US"}
# response = requests.get(url, headers=headers, params=querystring).json()
url = "https://api.twelvedata.com/time_series?symbol=BTC/USD&interval=1h&outputsize=200&apikey=1e883412b62940ccb48e5573b9b6a6f5"
response = requests.get(url, headers=headers)


In [3]:
response.json()['values']

[{'datetime': '2024-11-23 23:00:00',
  'open': '97761.05000',
  'high': '97902.98000',
  'low': '97505.32000',
  'close': '97660.23000'},
 {'datetime': '2024-11-23 22:00:00',
  'open': '98082.54000',
  'high': '98150.66000',
  'low': '97632.45000',
  'close': '97765.45000'},
 {'datetime': '2024-11-23 21:00:00',
  'open': '97838.41000',
  'high': '98159.99000',
  'low': '97660.01000',
  'close': '98082.55000'},
 {'datetime': '2024-11-23 20:00:00',
  'open': '97620.09000',
  'high': '97839.27000',
  'low': '97215.01000',
  'close': '97838.41000'},
 {'datetime': '2024-11-23 19:00:00',
  'open': '97976.27000',
  'high': '97976.28000',
  'low': '97500.00000',
  'close': '97620.09000'},
 {'datetime': '2024-11-23 18:00:00',
  'open': '98081.60000',
  'high': '98167.61000',
  'low': '97804.77000',
  'close': '97968.52000'},
 {'datetime': '2024-11-23 17:00:00',
  'open': '97874.73000',
  'high': '98266.55000',
  'low': '97500.01000',
  'close': '98081.60000'},
 {'datetime': '2024-11-23 16:00:00

In [4]:

response_df = pd.DataFrame(response.json()['values'])
response_df = response_df.rename(columns={'datetime':'date'}, errors="raise")

# for i in range(len(response_df)):
#     response_df.loc[i, 'datetime'] = datetime.datetime.fromtimestamp(response_df['datetime'][i])
# date = response_df['datetime']
response_df

exp = Exp(args)
exp.model.load_state_dict(torch.load(checkpoint_path, map_location=torch.device('cpu')))

Use CPU


<All keys matched successfully>

In [5]:
response_df

date         open         high          low        close
0    2024-11-23 23:00:00  97761.05000  97902.98000  97505.32000  97660.23000
1    2024-11-23 22:00:00  98082.54000  98150.66000  97632.45000  97765.45000
2    2024-11-23 21:00:00  97838.41000  98159.99000  97660.01000  98082.55000
3    2024-11-23 20:00:00  97620.09000  97839.27000  97215.01000  97838.41000
4    2024-11-23 19:00:00  97976.27000  97976.28000  97500.00000  97620.09000
..                   ...          ...          ...          ...          ...
195  2024-11-15 20:00:00  90400.33000  91541.67000  90357.70000  91523.12000
196  2024-11-15 19:00:00  89394.98000  90876.88000  89267.24000  90418.20000
197  2024-11-15 18:00:00  89493.38000  89847.37000  89211.05000  89394.97000
198  2024-11-15 17:00:00  89387.31000  89970.46000  89195.88000  89493.38000
199  2024-11-15 16:00:00  88440.25000  89752.02000  88376.42000  89385.04000

[200 rows x 5 columns]

In [6]:
# response_df.loc[response_df.index[i], 'volume_btc'] = response_df.loc[response_df.index[i], 'volume'] * response_df.loc[response_df.index[i], 'close']

columns = ['open','high','low','close']
for i in columns:
    response_df[i] = response_df[i].astype(float)

# response_df['volume_btc'] = response_df['close'] * response_df['volume']
# columns += 'volume_btc'
# df.to_csv('BTC-Hourly.csv', index=False)

In [7]:
std, mean = response_df.std(axis=0), response_df.mean(axis=0) 
normalized_data = pd.DataFrame()
normalized_data['date'] = response_df['date']
normalized_data[columns] = (response_df[columns] - mean) / std
normalized_data

date      open      high       low     close
0    2024-11-23 23:00:00  1.141120  1.084747  1.166052  1.101808
1    2024-11-23 22:00:00  1.235309  1.157958  1.203229  1.132742
2    2024-11-23 21:00:00  1.163784  1.160716  1.211289  1.225967
3    2024-11-23 20:00:00  1.099821  1.065915  1.081156  1.154192
4    2024-11-23 19:00:00  1.204174  1.106413  1.164496  1.090007
..                   ...       ...       ...       ...       ...
195  2024-11-15 20:00:00 -1.015408 -0.795572 -0.924153 -0.702463
196  2024-11-15 19:00:00 -1.309953 -0.992075 -1.243040 -1.027303
197  2024-11-15 18:00:00 -1.281124 -1.296385 -1.259472 -1.328126
198  2024-11-15 17:00:00 -1.312200 -1.260001 -1.263908 -1.299194
199  2024-11-15 16:00:00 -1.589668 -1.324569 -1.503546 -1.331045

[200 rows x 5 columns]

In [8]:
# predicted_changes = predict(exp, response_df)
# predicted_changes

In [13]:
# response_df = pd.DataFrame([response['prices'][i] for i in range(39, -1, -1)])
# for i in range(len(response_df)):
#     response_df.loc[i, 'date'] = datetime.datetime.fromtimestamp(response_df['date'][i])
# date = response_df['date']


aim = 'close'
Window = 42
middle = [0]*(len(response_df)-96)
exp.args.data_path = 'Temp.csv'
# columns = ['open','high','low','close','volume', 'volume_btc']
# response_df['date'] = np.nan
for i in range(96,len(normalized_data)):
    temp_df = pd.DataFrame(normalized_data[i-96:i])
    temp_df.to_csv('./data/Temp'+str(i)+'.csv', index=False)
for i in range(96,len(normalized_data)):
    args.data_path = 'Temp'+str(i)+'.csv'
    exp = Exp(args)
    exp.model.load_state_dict(torch.load(checkpoint_path, map_location=torch.device('cpu')))
    middle[i-96] = middle_band(exp)
# response_df['date'] = date
# response_df = response_df.set_index('date')

# response_df['middle_band'] = middle
# response_df['upper_band'], response_df['lower_band'] = bollinger_band(response_df['open'], response_df['middle_band'], 5, 3)  
   
# response_df.dropna(inplace=True)
# response_df[50:60]
middle

Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created!
pred 1
(12,)
Use CPU
data created

[array([-0.3       , -0.3       , -0.3       , -0.3       , -0.3       ,
         0.00729327, -0.07720549, -0.3       , -0.3       , -0.3       ,
        -0.3       , -0.3       ], dtype=float32),
 array([-0.3       , -0.3       , -0.3       , -0.3       , -0.3       ,
        -0.02711016, -0.09920646, -0.3       , -0.3       , -0.3       ,
        -0.3       , -0.3       ], dtype=float32),
 array([-0.3       , -0.3       , -0.3       , -0.3       , -0.3       ,
        -0.03908054, -0.10358712, -0.3       , -0.3       , -0.3       ,
        -0.3       , -0.3       ], dtype=float32),
 array([-0.3       , -0.3       , -0.3       , -0.3       , -0.3       ,
        -0.061647  , -0.13883585, -0.3       , -0.3       , -0.3       ,
        -0.3       , -0.3       ], dtype=float32),
 array([-0.3       , -0.3       , -0.3       , -0.3       , -0.3       ,
        -0.07152212, -0.1521225 , -0.3       , -0.3       , -0.3       ,
        -0.3       , -0.3       ], dtype=float32),
 array([-0.3   

In [17]:
middle = (pd.DataFrame(middle) * std[3]) + mean[3]
middle

0             1             2             3             4   \
0    92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   
1    92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   
2    92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   
3    92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   
4    92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   
..            ...           ...           ...           ...           ...   
99   92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   
100  92892.070312  92892.070312  92892.070312  92992.867188  92892.070312   
101  92892.070312  92892.070312  92892.070312  92905.101562  92892.070312   
102  92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   
103  92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   

               5             6             7             8             9   \
0    93937.304688  93649.890625  92892.070312  92892.070312  92892.070312   
1    93820.289062  93575.054688  92892.070312  92892.070312  92892.070312   
2    93779.570312  93560.156250  92892.070312  92892.070312  92892.070312   
3    93702.812500  93440.257812  92892.070312  92892.070312  92892.070312   
4    93669.218750  93395.062500  92892.070312  92892.070312  92892.070312   
..            ...           ...           ...           ...           ...   
99   92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   
100  92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   
101  92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   
102  92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   
103  92892.070312  92892.070312  92892.070312  92892.070312  92892.070312   

               10            11  
0    92892.070312  92892.070312  
1    92892.070312  92892.070312  
2    92892.070312  92892.070312  
3    92892.070312  92892.070312  
4    92892.070312  92892.070312  
..            ...           ...  
99   92892.070312  92892.070312  
100  93023.484375  93022.523438  
101  92946.835938  93021.453125  
102  92892.070312  92892.070312  
103  92892.070312  92892.070312  

[104 rows x 12 columns]

In [ ]:
env = TradingEnv(balance_amount=100,balance_unit='USDT', trading_fee_multiplier=0.99925)

for i in range(len(response_df)):
    if env.balance_unit == 'USDT':
        if response_df['low'].iloc[i] < response_df['lower_band'].iloc[i]: #buy signal
            env.buy(response_df['lower_band'].iloc[i], response_df.index[i])
            print(response_df.index[i].date(), "Покупка")
        else:
            print(response_df.index[i].date(), "Утримання")
    
                
    if env.balance_unit != 'USDT':
        if response_df['high'].iloc[i] > response_df['upper_band'].iloc[i]: #sell signal
            env.sell(response_df['upper_band'].iloc[i], response_df.index[i])
            print(response_df.index[i].date(), "Продаж")
        else:
            print(response_df.index[i].date(), "Утримання")
    

if env.balance_unit != 'USDT':
    env.sell(response_df['close'].iloc[-1], response_df.index[-1])

print(f'num buys: {len(env.buys)}')
print(f'num sells: {len(env.sells)}')
print(f'ending balance: {env.balance_amount} {env.balance_unit}')

plot_results(plot_df=response_df, buys=env.buys, sells=env.sells)

In [ ]:


class Dataset_Custom(Dataset):
    def __init__(self, root_path, flag='train', size=None, 
                 features='S', data_path='ETTh1.csv', 
                 target='OT', scale=True, inverse=False, timeenc=0, freq='h', cols=None):
        # size [seq_len, label_len, pred_len]
        # info
        if size == None:
            self.seq_len = 24*4*4
            self.label_len = 24*4
            self.pred_len = 24*4
        else:
            self.seq_len = size[0]
            self.label_len = size[1]
            self.pred_len = size[2]
        # init
        assert flag in ['train', 'test', 'val']
        type_map = {'train':0, 'val':1, 'test':2}
        self.set_type = type_map[flag]
        
        
data_dict = {'custom':Dataset_Custom,
}
Data = data_dict['custom']
Data

In [ ]:
from torch.utils.data import DataLoader, Dataset

class Dataset_Custom(Dataset):
    def __init__(self, root_path, flag='train', size=None, 
                 features='S', data_path='ETTh1.csv', 
                 target='OT', scale=True, inverse=False, timeenc=0, freq='h', cols=None):
        # size [seq_len, label_len, pred_len]
        # info
        if size == None:
            self.seq_len = 24*4*4
            self.label_len = 24*4
            self.pred_len = 24*4
        else:
            self.seq_len = size[0]
            self.label_len = size[1]
            self.pred_len = size[2]
        # init
        assert flag in ['train', 'test', 'val']
        type_map = {'train':0, 'val':1, 'test':2}
        self.set_type = type_map[flag]
        
        self.features = features
        self.target = target
        self.scale = scale
        self.inverse = inverse
        self.timeenc = timeenc
        self.freq = freq
        self.cols=cols
        self.root_path = root_path
        self.data_path = data_path
        self.__read_data__()

    def __read_data__(self):
        self.scaler = StandardScaler()
        df_raw = pd.read_csv(os.path.join(self.root_path,
                                          self.data_path))
        '''
        df_raw.columns: ['date', ...(other features), target feature]
        '''
        # cols = list(df_raw.columns); 
        if self.cols:
            cols=self.cols.copy()
            cols.remove(self.target)
        else:
            cols = list(df_raw.columns); cols.remove(self.target); cols.remove('date')
        df_raw = df_raw[['date']+cols+[self.target]]

        num_train = int(len(df_raw)*0.7)
        num_test = int(len(df_raw)*0.2)
        num_vali = len(df_raw) - num_train - num_test
        border1s = [0, num_train-self.seq_len, len(df_raw)-num_test-self.seq_len]
        border2s = [num_train, num_train+num_vali, len(df_raw)]
        border1 = border1s[self.set_type]
        border2 = border2s[self.set_type]
        
        if self.features=='M' or self.features=='MS':
            cols_data = df_raw.columns[1:]
            df_data = df_raw[cols_data]
        elif self.features=='S':
            df_data = df_raw[[self.target]]

        if self.scale:
            train_data = df_data[border1s[0]:border2s[0]]
            self.scaler.fit(train_data.values)
            data = self.scaler.transform(df_data.values)
        else:
            data = df_data.values
            
        df_stamp = df_raw[['date']][border1:border2]
        df_stamp['date'] = pd.to_datetime(df_stamp.date)
        data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)

        self.data_x = data[border1:border2]
        if self.inverse:
            self.data_y = df_data.values[border1:border2]
        else:
            self.data_y = data[border1:border2]
        self.data_stamp = data_stamp
    
    def __getitem__(self, index):
        s_begin = index
        s_end = s_begin + self.seq_len
        r_begin = s_end - self.label_len 
        r_end = r_begin + self.label_len + self.pred_len

        seq_x = self.data_x[s_begin:s_end]
        if self.inverse:
            seq_y = np.concatenate([self.data_x[r_begin:r_begin+self.label_len], self.data_y[r_begin+self.label_len:r_end]], 0)
        else:
            seq_y = self.data_y[r_begin:r_end]
        seq_x_mark = self.data_stamp[s_begin:s_end]
        seq_y_mark = self.data_stamp[r_begin:r_end]

        return seq_x, seq_y, seq_x_mark, seq_y_mark
    
    def __len__(self):
        return len(self.data_x) - self.seq_len- self.pred_len + 1

    def inverse_transform(self, data):
        return self.scaler.inverse_transform(data)

data_dict = {'custom':Dataset_Custom,
}
Data = data_dict['custom']

data_set = Data(
    root_path=args.root_path,
    data_path=args.data_path,
    flag=flag,
    size=[args.seq_len, args.label_len, args.pred_len],
    features=args.features,
    target=args.target,
    inverse=args.inverse,
    timeenc=timeenc,
    freq=freq,
    cols=args.cols
        )
print(flag, len(data_set))
data_loader = DataLoader(
    data_set,
    batch_size=batch_size,
    shuffle=shuffle_flag,
    num_workers=args.num_workers,
    drop_last=drop_last)

for i, (batch_x,batch_y,batch_x_mark,batch_y_mark) in enumerate(data_loader):
    batch_x = batch_x.float().to(torch.device('cpu'))
    batch_y = batch_y.float()
    batch_x_mark = batch_x_mark.float().to(torch.device('cpu'))
    batch_y_mark = batch_y_mark.float().to(torch.device('cpu'))

In [ ]:
pd.read_csv('./Temp.csv')

In [ ]:
args = exp.args

data_dict = {
    'ETTh1':Dataset_ETT_hour,
    'ETTh2':Dataset_ETT_hour,
    'ETTm1':Dataset_ETT_minute,
    'ETTm2':Dataset_ETT_minute,
    'WTH':Dataset_Custom,
    'ECL':Dataset_Custom,
    'Solar':Dataset_Custom,
    'custom':Dataset_Custom,
}
Data = data_dict[exp.args.data]
timeenc = 0 if args.embed!='timeF' else 1
Data
# if flag == 'test':
#     shuffle_flag = False; drop_last = True; batch_size = args.batch_size; freq=args.freq
# elif flag=='pred':
#     shuffle_flag = False; drop_last = False; batch_size = 1; freq=args.detail_freq
#     Data = Dataset_Pred
# else:
#     shuffle_flag = True; drop_last = True; batch_size = args.batch_size; freq=args.freq
# data_set = Data(
#     root_path=args.root_path,
#     data_path=args.data_path,
#     flag=flag,
#     size=[args.seq_len, args.label_len, args.pred_len],
#     features=args.features,
#     target=args.target,
#     inverse=args.inverse,
#     timeenc=timeenc,
#     freq=freq,
#     cols=args.cols